[package]
name = "otel_config_validator"
description = "Releaser for otel_config_validator"
version = "0.1.0"
license = "Apache-2.0"
repository = "https://github.com/open-telemetry/opentelemetry-configuration"
homepage = "https://opentelemetry.io/"
binaries = ["validator/otel_config_validator"]
build-command = ["make", "validator"]

# Config for 'cargo dist'
[dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = ["$OTEL_CONFIG_VALIDATOR_HOME/bin", "~/.local/bin"]
# Publish jobs to run in CI
pr-run-mode = "plan"
# A prefix git tags must include for cargo-dist to care about them
tag-namespace = "validator"
# Whether to install an updater program
install-updater = false
# Renovate starting pinning dependencies to a particular in https://github.com/open-telemetry/opentelemetry-configuration/pull/204
# This caused build failures since .github/workflows/validator-release.yml is generated and fails if the file contents have been
# modified. Right now, dist does not support pinned versions tags and thus we allow dirty as a workaround.
# See https://github.com/axodotdev/cargo-dist/issues/1800.
allow-dirty = ["ci"]

[dist.github-custom-runners]
global = "ubuntu-latest"

