[tools]

# Linters
"aqua:grafana/flint" = "0.22.8"
lychee = "0.24.2"

[tasks.lint]
description = "Run link checks"
raw_args = true
run = "flint run"

[tasks."lint:fix"]
description = "Auto-fix lint issues"
run = "flint run --fix"

[env]
FLINT_CONFIG_DIR = ".github/config"
