FROM ubuntu:22.04

RUN

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update \
    && apt-get install -y software-properties-common \
    && apt-add-repository ppa:rmescandon/yq \
    && apt-get update \
    && apt-get install -y shelltestrunner jq yq \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root

ENTRYPOINT ["shelltest"]
