name: Validator Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "stable"

      - name: Run govulncheck
        run: |
          make -C validator govulncheck

      # TODO: Publish releases
      - name: Build
        run: make validator

      - name: Test
        run: |
          cd validator
          go test .

      - name: Run ShellTests
        run: |
          make validator-run-shelltests
